name: 'Chalice Deployment'
description: 'This Github action allows automated deployment of your Chalice application via Github Actions.'
author: 'Hendrik Schafer <your-email@example.com>'
branding:
  icon: cloud
  color: yellow
runs:
  using: 'docker'
  image: 'Dockerfile'
